name: doxygen

on:
  push:
    branches:
      - doxy

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: doxy

      - name: run doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5